sudo: required
dist: trusty
language: node_js
node_js: stable

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 - npm install -g @angular/cli@latest
 - npm i webpack --save-dev

install:
  - npm install --prefix $TRAVIS_BUILD_DIR/weather-front

script:
  - cd $TRAVIS_BUILD_DIR/weather-front && ng build
  - cd $TRAVIS_BUILD_DIR/weather-front && ng test --watch=false

cache:
  directories:
    - $TRAVIS_BUILD_DIR/weather-front/node_modules

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
